theme: jekyll-theme-minimal
title: Dr. Konstantin Gavras
avatar: 'https://github.com/KostaGav/KostaGav.github.io/Gavras-Konstantin-github_small.jpg'
description: Nesto Software GmbH | Data Scientist | R & Python User
baseurl: 
