theme: jekyll-theme-minimal
title: Konstantin Gavras, PhD Student in Political Psychology
avatar: 'https://github.com/KostaGav/KostaGav.github.io/Gavras-Konstantin-github.jpg'
description: University of Mannheim | Data Enthusiast | R & Python User
