theme: jekyll-theme-minimal
title: Konstantin Gavras, PhD Student in Political Psychology
avatar: 'Gavras-Konstantin-github.jpg'
description: University of Mannheim | Data Enthusiast | R & Python User
